name: totp-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: totp build
      run: cd contrib/slapd-modules/passwd/totp && make
    - uses: actions/upload-artifact@v3
      with:
        name: totp_upload
        path: contrib/slapd-modules/passwd/totp/.libs/pw-totp.*
